[build]
    base = "frontend"
    command = "yarn run build"
    publish = "dist"

[build.environment]
    NODE_VERSION="16"
    YARN_VERSION = "1.22.1"
    YARN_FLAGS = "--production=false"
    NETLIFY_USE_YARN="true"
    VUE_APP_API_URL = "https://aiuto-server.herokuapp.com"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
