version: "3.9"

services:
  development-machine:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    container_name: AIuto

    volumes:
      - ..:/workspace/AIuto:cached
      - postgres_data:/workspace/.postgresql/pgsql/data

    command: sleep infinity

volumes:
  postgres_data:
